# db configuration
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=kh17
spring.datasource.password=kh17


#mybatis configuration
mybatis.type-aliases-package=com.kh.spring11.dto,com.kh.spring11.vo
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.mapper-locations=classpath:/mybatis/**/*-mapper.xml

#logging
logging.level.root=WARN
logging.level.com.kh=debug
logging.level.com.kh.spring.11.mapper=debug
logging.pattern.console=[%-5level] %msg - %c -%d{yyyy-MM-dd HH:mm:ss} %n

#jwt
custom.jwt.issuer=https://www.khacademy.co.kr/
custom.jwt.secret=12345678901234567890123456789012
custom.jwt.token-validity=1800
custom.jwt.refresh-token-validity=2419200